// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kuqciqsfoocaygtyhewh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1cWNpcXNmb29jYXlndHloZXdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxMDk3MTEsImV4cCI6MjA3MjY4NTcxMX0.s3iK7vV5_AkNR54eKjUsX0dJsPXoCVa1lPei1ng2BVM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});